name: NetworkLogin
main: net.zabszk.networklogin.Main
description: Zabszk Network Login Client
version: 1.0
author: zabszk
load: STARTUP

commands:
   login:
      description: Logs you in.
      usage: /login <password>
      aliases: [l, signin]
   logout:
      description: Logs you out.
      usage: /logout
      aliases: signout